README.md, composer.json
=> Some tweaks

app/View/Components/App.php, resources/views/partials/navbar.blade.php
This should probably be configurable or completely custom at some point but sorting by title makes more sense than the default (no order) at the moment.
=> Order projects in navbar by title

README.md, app/Providers/AppServiceProvider.php, app/Services/OgImage.php, app/Services/OgImageGenerator.php, app/SocialProviders/SsoProvider.php, app/Traits/HasOgImage.php, composer.json, database/settings/2022_05_28_135244_add_block_robots_setting.php, resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php, routes/web.php, tests/Unit/Services/OgImageGeneratorTest.php
Misschien beetje overdreven, maar misschien beter zo... kijk maar of je het wat vind 😉
=> OG refactor

tests/Feature/Auth/LoginTest.php, tests/Feature/Auth/RegistrationTest.php, tests/Feature/Auth/ResetPasswordTest.php
Added tests covering login, registration and password resetting.
=> Added auth tests

app/Http/Controllers/ItemController.php, app/Http/Livewire/Item/Comments.php, app/Http/Livewire/Profile.php, app/Models/Comment.php, app/Models/User.php, app/Notifications/CommentHasReplyNotification.php, app/Observers/CommentObserver.php, database/migrations/2022_06_05_223148_add_parent_id_to_comments_table.php, lang/en/comments.php, lang/en/profile.php, lang/nl/comments.php, lang/nl/profile.php, resources/views/components/comment.blade.php, resources/views/livewire/item/comments.blade.php
=> Reply on comments

app/Filament/Resources/InboxResource.php, app/Filament/Resources/ItemResource.php, app/Http/Controllers/ProjectController.php, app/Http/Livewire/Project/Items.php, app/Models/Item.php, app/Observers/ItemObserver.php, app/Providers/AppServiceProvider.php, database/migrations/2022_05_03_074737_create_items_table.php, database/migrations/2022_06_13_142538_add_pin_to_items.php, resources/views/livewire/board/item-card.blade.php, resources/views/project.blade.php
=> Pin items 

resources/views/partials/header.blade.php
=> add item add button to mobile nav

app/Http/Livewire/Modals/Item/CreateItemModal.php, resources/views/livewire/modals/create-item-modal.blade.php
this pr attempts to address #31, I was unsure if the list should be added to the create screen in the filament dashboard.
=> add list of similar items to create item modal

app/Filament/Resources/ItemResource.php, app/Filament/Widgets/LatestItems.php, app/Filament/Widgets/PopularItems.php, app/Http/Controllers/ItemController.php, app/Http/Controllers/ProjectController.php, app/Http/Livewire/Modals/Item/CreateItemModal.php, app/Http/Livewire/Welcome/RecentItems.php, app/Models/Item.php, app/Observers/ItemObserver.php, database/migrations/2022_06_18_084743_add_private_column_to_items_table.php, lang/en/items.php, lang/nl/items.php, resources/views/item.blade.php, resources/views/livewire/board/item-card.blade.php, resources/views/project.blade.php
Private items will only be visible for admins and employees.
=> Possibility to make items private

app/Filament/Resources/ItemResource/RelationManagers/ActivitiesRelationManager.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/RelationManagers/VotesRelationManager.php, app/Policies/VotePolicy.php
This makes it possible to manually add votes from within the admin, edit the subscribed status per vote, and delete a vote.
=> Manage votes within the admin

app/Filament/Pages/Settings.php, app/Settings/GeneralSettings.php, composer.json, composer.lock, database/settings/2022_06_19_172203_add_custom_scripts_setting.php, resources/views/components/app.blade.php
Option to add custom scripts to add a support widget for example
=> Custom scripts setting

app/Http/Livewire/Item/Comments.php, app/Models/Comment.php, composer.lock, database/migrations/2022_06_20_112935_add_private_column_to_comments_table.php, lang/en/comments.php, lang/nl/comments.php, resources/views/components/comment.blade.php
=> Private comments

app/Mail/Admin/ItemHasBeenCreatedEmail.php
This explained why I never got these e-mails :)
=> Set `to` not `from` on item created notification

app/Http/Livewire/Modals/Item/CreateItemModal.php, app/Spotlight/CreateItem.php, config/livewire-ui-spotlight.php, lang/en/spotlight.php
Fixes https://github.com/ploi-deploy/roadmap/issues/89
- Create new item command added
- Autofocus on first input in the create item modal
- Fixed typo
=> Keyboard workflow enhancements

app/Http/Livewire/Item/Comments.php, app/Http/Livewire/Modals/Item/Comment/EditCommentModal.php, app/Http/Livewire/Modals/Item/Comment/ShowCommentActivitiesModal.php, app/Models/Comment.php, lang/en/comments.php, lang/en/general.php, lang/en/table.php, lang/nl/comments.php, lang/nl/general.php, lang/nl/table.php, resources/views/components/comment.blade.php, resources/views/livewire/modals/items/comments/edit.blade.php, resources/views/livewire/modals/items/comments/show-activitylog.blade.php
=> Edit own comments

app/Filament/Pages/Settings.php, app/Http/Livewire/Item/VoteButton.php, app/Models/Item.php, app/Settings/GeneralSettings.php, database/settings/2022_06_22_160414_add_toggle_for_voter_avatars_in_item_view.php, resources/views/livewire/item/vote-button.blade.php, tests/Unit/Models/ItemTest.php
=> Toggleable voter avatars

app/Models/User.php, config/services.php
This allows the use of a Gravatar proxy for example.
=> Allow changing the Gravatar base URL

app/Filament/Resources/ItemResource.php, app/Filament/Resources/ItemResource/Pages/EditItem.php, app/Models/Item.php, app/Observers/ItemObserver.php, database/migrations/2022_06_30_100948_add_notify_subscribers_column_to_items_table.php
=> Notify subscribers setting

resources/views/livewire/modals/items/comments/show-activitylog.blade.php
=> Comment history fix

app/Http/Livewire/Modals/Item/Comment/EditCommentModal.php, resources/views/livewire/modals/items/comments/show-activitylog.blade.php
=> Fix comments history

.github/workflows/php_test.yml, .gitignore, app/Providers/AppServiceProvider.php, composer.lock, package-lock.json, package.json, postcss.config.js, resources/css/fonts.css, resources/js/app.js, resources/views/components/app.blade.php, vite.config.js, yarn.lock
=> Move from mix to Vite

app/Filament/Resources/ProjectResource.php, app/Models/Project.php, app/Services/Icons.php, composer.lock, database/migrations/2022_07_10_144807_add_icon_to_projects_table.php, resources/views/partials/navbar.blade.php, tests/Feature/Services/IconsTest.php, yarn.lock
=> Select custom project icons

app/Filament/Pages/System.php, app/Filament/Resources/ChangelogResource.php, app/Filament/Resources/ChangelogResource/Pages/CreateChangelog.php, app/Filament/Resources/ChangelogResource/Pages/EditChangelog.php, app/Filament/Resources/ChangelogResource/Pages/ListChangelogs.php, app/Filament/Resources/ItemResource/RelationManagers/ChangelogsRelationManager.php, app/Http/Controllers/ChangelogController.php, app/Http/Livewire/Changelog/Item.php, app/Http/Livewire/Item/Create.php, app/Http/Livewire/Item/Edit.php, app/Models/Changelog.php, app/Notifications/Item/ItemHasNewCommentNotification.php, app/Notifications/Item/ItemUpdatedNotification.php, app/Providers/AppServiceProvider.php, app/Providers/EventServiceProvider.php, database/factories/ProjectFactory.php, database/migrations/2022_06_27_160827_create_changelog_table.php, database/migrations/2022_06_30_100948_add_notify_subscribers_column_to_items_table.php, phpunit.xml, routes/web.php, tests/Feature/Controllers/BoardsControllerTest.php, tests/Feature/Controllers/ItemControllerTest.php, tests/Feature/Item/CreateItemTest.php, tests/Pest.php, tests/Unit/Models/ItemTest.php
This has not been done in a long while :)
Also a fix (for when SSO is forced) that breaks the tests.
Maybe we should have a GitHub action checking if `composer format` did run before you can merge. I'm personally not a fan of GitHub actions that autocommit running `composer format`, but that is also an option.
=> Run composer format

README.md, app/Console/Commands/Concerns/CanShowAnIntro.php, app/Console/Commands/Install.php, app/Console/Commands/Upgrade.php, app/Filament/Resources/ProjectResource.php, database/migrations/2022_07_10_144807_add_icon_to_projects_table.php, tests/Feature/Services/IconsTest.php
=> Create roadmap upgrade command

app/Filament/Resources/ProjectResource.php, app/Filament/Resources/ProjectResource/Pages/ListProjects.php, app/Models/Project.php, app/View/Components/App.php, composer.lock, database/migrations/2022_07_26_035141_add_sort_order_to_projects_table.php
=> Make projects sortable

app/Models/User.php, resources/views/livewire/modals/items/create.blade.php, tests/Feature/Livewire/Modals/Item/CreateItemModalTest.php, tests/Unit/Models/UserTest.php
=> Show email verification message in modal if needed.

app/Http/Controllers/Auth/LoginController.php
=> Automatically confirm users created through SSO

app/Http/Livewire/My.php
=> "My items" tables sorting doesn't work except for the last table

.env.example, README.md, app/SocialProviders/SsoProvider.php, config/services.php
=> Added more tweaks to SSO

app/Http/Livewire/My.php, app/Http/Livewire/Profile.php, app/Http/Livewire/RecentMentions.php, app/Models/User.php, database/migrations/2022_08_26_195053_add_per_page_setting_to_user_table.php, lang/en/profile.php
This address #131,
I have set the db field as nullable for sqlite and used 5 per page as a default when none is set by the user.
=> Per page setting attempt 2

app/Http/Controllers/ItemController.php, lang/en/items.php, lang/nl/items.php, resources/views/item.blade.php, routes/web.php, tests/Feature/Controllers/ItemControllerTest.php
=> Make it possible for admins to change board in item view

.env.example, app/Http/Livewire/Modals/Item/CreateItemModal.php, app/Observers/ItemObserver.php, config/filament.php, config/notifications.php, database/migrations/2022_09_14_052900_create_notifications_table.php, lang/en/items.php, lang/en/notifications.php, lang/nl/items.php, lang/nl/notifications.php
This PR allows the new Filament database notifications to be used. When a new item is submitted, you'll now receive a notification inside the admin panel as well.
This is configurable per `.env` file setting:
`APP_ADMIN_NOTIFICATIONS=true`
=> Database notifications

app/Http/Livewire/Item/VoteButton.php, app/Models/Comment.php, app/Models/Item.php, app/Traits/HasUpvote.php, database/migrations/2022_09_30_195933_add_total_votes_to_comments_table.php, resources/views/components/comment.blade.php, resources/views/item.blade.php, resources/views/livewire/item/vote-button.blade.php, tests/Feature/Controllers/ItemControllerTest.php
=> Add ability to upvote comments

app/Filament/Resources/ItemResource.php, app/Filament/Resources/TagResource.php, app/Filament/Resources/TagResource/Pages/CreateTag.php, app/Filament/Resources/TagResource/Pages/EditTag.php, app/Filament/Resources/TagResource/Pages/ListTags.php, app/Http/Controllers/ItemController.php, app/Models/Item.php, composer.json, composer.lock, database/migrations/2022_10_02_121026_create_tag_tables.php, resources/views/components/tag.blade.php, resources/views/item.blade.php
Closes #99 
Frontend:
Backend:
=> Ability to add tags for item

app/Http/Kernel.php, app/Http/Livewire/Profile.php, app/Http/Middleware/Localize.php, app/Models/User.php, database/migrations/2022_10_18_112136_add_locale_to_users_table.php, lang/en/auth.php, lang/nl/auth.php
=> User editable locale

app/Filament/Resources/ProjectResource.php, app/Models/Project.php, app/Models/ProjectMember.php, app/Models/User.php, database/migrations/2022_10_18_173054_create_project_member_table.php
=> Give users access to a private project

app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/RelationManagers/ProjectsRelationManager.php, lang/en/projects.php, lang/nl/projects.php
Also it only shows the relation manager when there are private projects
=> Ability to add a project to a user via the user resource

app/Exceptions/Handler.php, app/Http/Controllers/ItemEmailUnsubscribeController.php, app/Models/User.php, app/Notifications/Item/ItemHasNewCommentNotification.php, app/Notifications/Item/ItemUpdatedNotification.php, lang/en/errors.php, lang/en/notifications.php, resources/views/emails/item/new-comment.blade.php, resources/views/emails/item/updated.blade.php, resources/views/errors/link-expired.blade.php, routes/web.php, tests/Feature/Controllers/ItemEmailUnsubscribeControllerTest.php, tests/Unit/Models/UserTest.php
Adds an easy way to unsubscribe from items directly from the email.
=> Feature: item email unsubscribe link

app/Filament/Pages/Settings.php, app/Observers/ItemObserver.php
Sometimes, you’re going to want to explicitly notify per project, with this PR you can.
=> Allow notifications per project

app/Http/Middleware/PasswordProtected.php
Option to add `?secret=` to the url to bypass the password screen
=> option to bypass the password by setting the secret route parameter

app/Http/Livewire/Welcome/RecentComments.php
It's useful to open the item while you read the recent comments.
=> added the url to the item column of the recent-comments widget

app/Filament/Pages/Colors.php, app/Settings/ColorSettings.php, app/View/Components/App.php, database/settings/2023_03_28_182052_add_font_family.php, resources/css/app.css, resources/views/components/app.blade.php
Adds support for defining a custom font family to expand customisation settings.
=> Add support for custom font family

app/Filament/Resources/ItemResource.php
=> Fixes #224

app/Models/Comment.php, resources/views/livewire/modals/items/comments/show-activitylog.blade.php
=> Don't log when voting on a comment

app/Livewire/Header.php
=> Users can select forbidden boards

app/Livewire/Header.php
=> Boards are not assigned

app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Pages/EditUser.php, app/Models/User.php, composer.json, composer.lock, resources/views/components/app.blade.php
=> Add impersonate

app/Http/Controllers/BoardsController.php
=> Permission fix

app/Http/Controllers/ItemController.php, app/Http/Controllers/SitemapController.php, app/Models/Item.php, composer.json, composer.lock, resources/views/board.blade.php, resources/views/changelog.blade.php, resources/views/edit-item.blade.php, resources/views/item.blade.php, resources/views/partials/meta.blade.php, resources/views/project.blade.php, resources/views/welcome.blade.php, routes/web.php
Follow-up from https://github.com/ploi/roadmap/pull/248 to redirect the user (and bots) to the correct page for the content.
=> Add canonical html tag to the views

tests/Feature/Controllers/MyControllerTest.php
The test failed when we had a different lang.
=> Fix test for translations

composer.json, composer.lock
https://github.com/filamentphp/filament/releases/tag/v3.2.115
=> Security patch
